const MANIFEST='./videos.json';
const RAW='https://media.githubusercontent.com/media/LaxmanNepal/Videos/main/course/youtube/';
const KEY={done:'laxman-youtube-course-done-v2',pos:'laxman-youtube-course-position-v2',last:'laxman-youtube-last-lesson-v2',speed:'laxman-youtube-speed-v2',volume:'laxman-youtube-volume-v2',notes:'laxman-youtube-notes-v2',started:'laxman-youtube-started-v2'};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const player=$('#player'),list=$('#lessonList'),search=$('#search'),title=$('#lessonTitle'),meta=$('#lessonMeta'),num=$('#lessonNumber');
const progress=$('#progressText'),ring=$('#ring'),playlistMeta=$('#playlistMeta'),prev=$('#prevBtn'),next=$('#nextBtn'),overlay=$('#playerOverlay'),themeBtn=$('#themeBtn'),courseGrid=$('#courseGrid');
const wrap=$('#videoWrap'),playBtn=$('#playBtn'),muteBtn=$('#muteBtn'),speedBtn=$('#speedBtn'),pipBtn=$('#pipBtn'),theaterBtn=$('#theaterBtn'),fullscreenBtn=$('#fullscreenBtn'),seek=$('#seek'),timeDisplay=$('#timeDisplay'),speedMenu=$('#speedMenu'),toast=$('#videoToast');
let lessons=[],current=0,controlsTimer,resumeTimer,endTimer,saveTimer;
let done=read(KEY.done,[]),positions=read(KEY.pos,{}),last=Number(localStorage.getItem(KEY.last));
function read(k,f){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function cleanName(n){return n.replace(/\.mp4$/i,'').replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim()}
function natural(a,b){return a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'})}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function pct(){return lessons.length?Math.round(done.filter(i=>i<lessons.length).length/lessons.length*100):0}
function fmt(t){if(!Number.isFinite(t)||t<0)return'0:00';const h=Math.floor(t/3600),m=Math.floor(t%3600/60),s=Math.floor(t%60).toString().padStart(2,'0');return h?`${h}:${String(m).padStart(2,'0')}:${s}`:`${m}:${s}`}
function toastMsg(x,ms=1600){if(!toast)return;toast.textContent=x;toast.classList.add('show');clearTimeout(toastMsg.t);toastMsg.t=setTimeout(()=>toast.classList.remove('show'),ms)}
function updateProgress(){const p=pct(),c=done.filter(i=>i<lessons.length).length;if(progress)progress.textContent=p+'%';if(ring)ring.textContent=p+'%';if(playlistMeta)playlistMeta.textContent=`${c} of ${lessons.length} completed`;
  ['dashboardProgress','dashProgress','heroProgress'].forEach(id=>{const e=$('#'+id);if(e)e.textContent=p+'%'});
  const cEl=$('#dashCompleted');if(cEl)cEl.textContent=c;const rEl=$('#dashRemaining');if(rEl)rEl.textContent=Math.max(0,lessons.length-c);const lEl=$('#dashLessons');if(lEl)lEl.textContent=lessons.length;
}
function markComplete(i=current,manual=true){if(i<0||!lessons[i])return;if(!done.includes(i)){done.push(i);done.sort((a,b)=>a-b);write(KEY.done,done);delete positions[i];write(KEY.pos,positions);render();courseCard();updateProgress();if(manual)toastMsg('✓ Lesson completed');if(pct()===100)showCertificate();}}
function lastWatched(){if(Number.isInteger(last)&&last>=0&&last<lessons.length)return last;const keys=Object.keys(positions).map(Number).filter(i=>i<lessons.length&&positions[i]>5);return keys[0]}
function resumeIndex(){const l=lastWatched();if(l!==undefined&&!done.includes(l))return l;const n=lessons.findIndex((_,i)=>!done.includes(i));return n<0?0:n}
function courseCard(){if(!courseGrid)return;const p=pct(),completed=done.filter(i=>i<lessons.length).length,start=resumeIndex(),resume=lessons[start];const label=p>=100?'Review Course':completed?'Continue Course':'Start Course';courseGrid.innerHTML=`<article class="course-card dynamic-card"><a class="course-cover" href="lesson.html?lesson=${start}"><div class="cover-orbit"></div><div class="cover-grid"></div><span class="cover-badge">CREATOR ACADEMY</span><div class="cover-content"><small>YOUTUBE</small><strong>CREATOR<br>COURSE</strong><span>FILM · EDIT · GROW</span></div><div class="cover-play">▶</div></a><div class="course-body"><div class="course-heading"><div><span class="course-eyebrow">FEATURED COURSE</span><h3>YouTube Creator Course</h3><p>From filming and lighting to editing, publishing and growing an audience.</p></div><span class="course-state">${p}%</span></div><div class="course-progress"><div><span>${completed} of ${lessons.length} lessons completed</span><b>${p}%</b></div><i><u style="width:${p}%"></u></i></div><div class="course-resume">${resume?`${completed?'Continue':'Start'} with Lesson ${start+1}: ${esc(resume.title)}`:'Your lessons are ready'}</div><div class="course-actions"><a class="course-link primary-course" href="lesson.html?lesson=${start}">${label} <span>→</span></a><span class="course-meta-text">${lessons.length} lessons · Self-paced</span></div></div></article>`}
function moduleFor(i){const t=(lessons[i]?.title||'').toLowerCase();if(/edit|software|footage/.test(t))return'Editing';if(/light/.test(t))return'Lighting';if(/audio/.test(t))return'Audio';if(/publish|cre formula|hobby|adsense|brand|sponsor|affiliate|donation/.test(t))return'Growth & Monetization';if(/shoot|film/.test(t))return'Production';return'Foundations & Content'}
function render(){if(!list)return;const q=(search?.value||'').trim().toLowerCase(),filter=$('#moduleFilter')?.value||'all';list.innerHTML='';lessons.forEach((l,i)=>{if(q&&!l.title.toLowerCase().includes(q))return;if(filter!=='all'&&moduleFor(i)!==filter)return;const b=document.createElement('button');const position=positions[i]||0;b.className='lesson '+(i===current?'active ':'')+(done.includes(i)?'done':'');b.innerHTML=`<span class="lesson-num">${String(i+1).padStart(2,'0')}</span><span class="lesson-copy"><span class="lesson-title">${esc(l.title)}</span><span class="lesson-status">${done.includes(i)?'✓ Completed':position>5?`Resume ${fmt(position)}`:'Watch lesson'} · ${moduleFor(i)}</span></span>`;b.onclick=()=>select(i,false);list.appendChild(b)});updateProgress()}
function setResumeUI(i){const p=positions[i]||0;if(!p||done.includes(i))return;const box=$('#resumeBox');if(!box)return;$('#resumeTime').textContent=fmt(p);box.classList.add('show');clearTimeout(resumeTimer);resumeTimer=setTimeout(()=>box.classList.remove('show'),7000)}
function select(i,autoplay=false){if(!lessons[i])return;clearTimeout(endTimer);current=i;last=i;localStorage.setItem(KEY.last,String(i));write(KEY.started,1);if(title)title.textContent=lessons[i].title;if(num)num.textContent='LESSON '+String(i+1).padStart(2,'0');if(meta)meta.textContent=`Lesson ${i+1} of ${lessons.length} · ${moduleFor(i)}`;if(prev)prev.disabled=i===0;if(next)next.disabled=i===lessons.length-1;if(player){player.pause();player.src=lessons[i].url||RAW+encodeURIComponent(lessons[i].name);player.load();player.addEventListener('loadedmetadata',()=>{try{player.currentTime=positions[i]||0}catch{}updateControls();setResumeUI(i);if(autoplay)player.play().catch(()=>{});},{once:true})}if(overlay)overlay.classList.remove('hidden');render();updateLessonExtra()}
function updateLessonExtra(){const e=$('#lessonModule');if(e)e.textContent=moduleFor(current);const d=$('#lessonDoneBtn');if(d){d.textContent=done.includes(current)?'✓ Completed':'Mark complete';d.classList.toggle('is-done',done.includes(current))}const n=$('#notes');if(n)n.value=read(KEY.notes,{})[current]||''}
function updateControls(){if(!player)return;const d=player.duration||0,t=player.currentTime||0;if(seek)seek.value=d?Math.round(t/d*1000):0;if(timeDisplay)timeDisplay.textContent=`${fmt(t)} / ${fmt(d)}`;if(playBtn)playBtn.textContent=player.paused?'▶':'❚❚';if(muteBtn)muteBtn.textContent=player.muted||player.volume===0?'🔇':'🔊';if(speedBtn)speedBtn.textContent=(player.playbackRate||1)+'×'}
function togglePlay(){if(!player)return;if(player.paused){player.play().catch(()=>{});toastMsg('Playing')}else{player.pause();toastMsg('Paused')}}
function showEndScreen(){const e=$('#endScreen');if(!e)return;const n=current+1;if(n<lessons.length){$('#endNextTitle').textContent=lessons[n].title;let s=6;$('#endCountdown').textContent=s;clearInterval(endTimer);endTimer=setInterval(()=>{s--;if($('#endCountdown'))$('#endCountdown').textContent=s;if(s<=0){clearInterval(endTimer);select(n,true);e.classList.remove('show')}},1000);e.classList.add('show')}else{e.classList.add('show');const h=$('#endNextTitle');if(h)h.textContent='Course complete — congratulations!';if($('#endCountdown'))$('#endCountdown').textContent='✓'}}
function showCertificate(){const c=$('#certificate');if(c)c.classList.add('show')}
player?.addEventListener('loadedmetadata',()=>{updateControls();const saved=localStorage.getItem(KEY.volume);let v=saved===null?1:Number(saved);if(saved==='0'){v=1;localStorage.setItem(KEY.volume,'1')}if(Number.isFinite(v)){player.volume=Math.max(0,Math.min(1,v));player.muted=false}});
player?.addEventListener('timeupdate',()=>{updateControls();if(!lessons[current])return;last=current;localStorage.setItem(KEY.last,String(current));if(player.currentTime>2&&!done.includes(current)){positions[current]=Math.floor(player.currentTime);write(KEY.pos,positions);if(player.duration&&player.currentTime/player.duration>=.9)markComplete(current,false)}clearTimeout(saveTimer);saveTimer=setTimeout(()=>courseCard(),500)});
player?.addEventListener('play',()=>{overlay?.classList.add('hidden');$('#resumeBox')?.classList.remove('show');updateControls()});
player?.addEventListener('pause',updateControls);
player?.addEventListener('waiting',()=>wrap?.classList.add('buffering'));
player?.addEventListener('canplay',()=>wrap?.classList.remove('buffering'));
player?.addEventListener('ended',()=>{markComplete(current,false);showEndScreen();});
player?.addEventListener('error',()=>{wrap?.classList.remove('buffering');toastMsg('Video could not be loaded — try again')});
playBtn?.addEventListener('click',togglePlay);overlay?.addEventListener('click',togglePlay);seek?.addEventListener('input',()=>{if(player.duration)player.currentTime=Number(seek.value)/1000*player.duration});
muteBtn?.addEventListener('click',()=>{player.muted=!player.muted;localStorage.setItem(KEY.volume,String(player.muted?0:player.volume||1));updateControls()});
player?.addEventListener('volumechange',()=>localStorage.setItem(KEY.volume,String(player.muted?0:player.volume));
speedBtn?.addEventListener('click',()=>speedMenu?.classList.toggle('open'));speedMenu?.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{const s=Number(b.dataset.speed);player.playbackRate=s;localStorage.setItem(KEY.speed,String(s));if(speedBtn)speedBtn.textContent=s+'×';speedMenu.classList.remove('open')}));
pipBtn?.addEventListener('click',async()=>{try{if(document.pictureInPictureElement)await document.exitPictureInPicture();else await player.requestPictureInPicture()}catch{toastMsg('PiP unavailable')}});
theaterBtn?.addEventListener('click',()=>wrap?.classList.toggle('theater'));fullscreenBtn?.addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await wrap.requestFullscreen()}catch{}});
wrap?.addEventListener('mousemove',()=>{wrap.classList.add('controls-visible');clearTimeout(controlsTimer);controlsTimer=setTimeout(()=>{if(player&&!player.paused)wrap.classList.remove('controls-visible')},2500)});
$('#back10Btn')?.addEventListener('click',()=>jump(-10));$('#forward10Btn')?.addEventListener('click',()=>jump(10));function jump(s){if(!player)return;player.currentTime=Math.max(0,Math.min(player.duration||Infinity,player.currentTime+s));const h=$('#skipHint');if(h){h.textContent=s<0?'↶ 10 seconds':'↷ 10 seconds';h.classList.remove('show');void h.offsetWidth;h.classList.add('show')}}
prev?.addEventListener('click',()=>select(Math.max(0,current-1)));next?.addEventListener('click',()=>select(Math.min(lessons.length-1,current+1),true));search?.addEventListener('input',render);$('#moduleFilter')?.addEventListener('change',render);
$('#lessonDoneBtn')?.addEventListener('click',()=>markComplete(current,true));$('#resumeContinue')?.addEventListener('click',()=>{$('#resumeBox')?.classList.remove('show');if(player)player.play().catch(()=>{})});$('#resumeRestart')?.addEventListener('click',()=>{positions[current]=0;write(KEY.pos,positions);if(player)player.currentTime=0;$('#resumeBox')?.classList.remove('show');if(player)player.play().catch(()=>{})});$('#endCancel')?.addEventListener('click',()=>{clearInterval(endTimer);$('#endScreen')?.classList.remove('show')});$('#endNext')?.addEventListener('click',()=>{clearInterval(endTimer);$('#endScreen')?.classList.remove('show');if(current<lessons.length-1)select(current+1,true)});
$('#notes')?.addEventListener('input',e=>{const n=read(KEY.notes,{});n[current]=e.target.value;write(KEY.notes,n)});
$('#clearProgress')?.addEventListener('click',()=>{if(confirm('Reset all course progress on this browser?')){done=[];positions={};localStorage.removeItem(KEY.last);write(KEY.done,done);write(KEY.pos,positions);updateLessonExtra();render();courseCard();toastMsg('Progress reset')}});
themeBtn?.addEventListener('click',()=>{document.body.classList.toggle('light');localStorage.setItem('course-theme',document.body.classList.contains('light')?'light':'dark')});if(localStorage.getItem('course-theme')==='light')document.body.classList.add('light');
function loadSpeed(){const s=Number(localStorage.getItem(KEY.speed));if(player&&[.75,1,1.25,1.5,1.75,2].includes(s))player.playbackRate=s}
document.addEventListener('keydown',e=>{if(!player||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(e.code==='Space'){e.preventDefault();togglePlay()}else if(e.key==='ArrowRight')jump(5);else if(e.key==='ArrowLeft')jump(-5);else if(e.key.toLowerCase()==='m')muteBtn?.click();else if(e.key.toLowerCase()==='f')fullscreenBtn?.click();else if(e.key.toLowerCase()==='t')theaterBtn?.click()});
async function load(){try{const r=await fetch(MANIFEST+'?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('Manifest '+r.status);const files=await r.json();lessons=files.filter(x=>x.name&&/\.mp4$/i.test(x.name)).map(x=>({...x,title:x.title||cleanName(x.name),url:x.url||RAW+encodeURIComponent(x.name)})).sort(natural);const h=$('#heroLessons');if(h)h.textContent=lessons.length;const cc=$('#courseCount');if(cc)cc.textContent='1';courseCard();render();updateProgress();if(player){const q=new URLSearchParams(location.search);let i=Number(q.get('lesson'));if(!Number.isInteger(i)||i<0||i>=lessons.length)i=resumeIndex();select(i);loadSpeed()}}catch(e){console.error(e);if(list)list.innerHTML='<div style="padding:20px;color:#9aa3b2">Course manifest unavailable. Refresh in a moment.</div>'}}
load();
