const MANIFEST='./videos.json';
const RAW='https://media.githubusercontent.com/media/LaxmanNepal/Videos/main/course/youtube/';
const player=document.querySelector('#player'),list=document.querySelector('#lessonList'),search=document.querySelector('#search');
const title=document.querySelector('#lessonTitle'),meta=document.querySelector('#lessonMeta'),num=document.querySelector('#lessonNumber');
const progress=document.querySelector('#progressText'),ring=document.querySelector('#ring'),playlistMeta=document.querySelector('#playlistMeta');
const prev=document.querySelector('#prevBtn'),next=document.querySelector('#nextBtn'),overlay=document.querySelector('#playerOverlay'),themeBtn=document.querySelector('#themeBtn');
const courseGrid=document.querySelector('#courseGrid'),courseCount=document.querySelector('#courseCount'),featuredCount=document.querySelector('#featuredCount'),startCourse=document.querySelector('#startCourse');
const wrap=document.querySelector('#videoWrap'),playBtn=document.querySelector('#playBtn'),muteBtn=document.querySelector('#muteBtn'),speedBtn=document.querySelector('#speedBtn'),pipBtn=document.querySelector('#pipBtn'),theaterBtn=document.querySelector('#theaterBtn'),fullscreenBtn=document.querySelector('#fullscreenBtn'),seek=document.querySelector('#seek'),timeDisplay=document.querySelector('#timeDisplay'),speedMenu=document.querySelector('#speedMenu'),toast=document.querySelector('#videoToast');
let lessons=[],current=0,controlsTimer;
const doneKey='laxman-youtube-course-done-v1',posKey='laxman-youtube-course-position-v1';
let done=JSON.parse(localStorage.getItem(doneKey)||'[]'),positions=JSON.parse(localStorage.getItem(posKey)||'{}');
function cleanName(name){return name.replace(/\.mp4$/i,'').replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim()}
function natural(a,b){return a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'})}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function thumb(l,i){return l.thumbnail||`https://picsum.photos/seed/laxman-course-${i+1}/640/360`}
function pct(){return lessons.length?Math.round(done.filter(i=>i<lessons.length).length/lessons.length*100):0}
function updateProgress(){const p=pct(),c=done.filter(i=>i<lessons.length).length;if(progress)progress.textContent=p+'%';if(ring)ring.textContent=p+'%';if(playlistMeta)playlistMeta.textContent=`${c} of ${lessons.length} completed`;const d=document.querySelector('#dashboardProgress');if(d)d.textContent=p+'%';const b=document.querySelector('#dashboardBar');if(b)b.style.width=p+'%';const h=document.querySelector('#heroProgress');if(h)h.textContent=p+'%';const hc=document.querySelector('#heroCompleted');if(hc)hc.textContent=c}
function render(){if(!list)return;const q=(search?.value||'').trim().toLowerCase();list.innerHTML='';lessons.forEach((l,i)=>{if(q&&!l.title.toLowerCase().includes(q))return;const b=document.createElement('button');b.className='lesson '+(i===current?'active ':'')+(done.includes(i)?'done':'');b.innerHTML=`<span class="lesson-num">${String(i+1).padStart(2,'0')}</span><span class="lesson-copy"><span class="lesson-title">${esc(l.title)}</span><span class="lesson-status">${done.includes(i)?'✓ Completed':'Watch lesson'}</span></span>`;b.onclick=()=>select(i);list.appendChild(b)});updateProgress()}
function select(i,autoplay=false){if(!lessons[i])return;current=i;if(player){player.pause();player.src=lessons[i].url||RAW+encodeURIComponent(lessons[i].name);player.load();player.addEventListener('loadedmetadata',()=>{try{player.currentTime=positions[i]||0}catch(e){}if(autoplay)player.play().catch(()=>{});updateControls()},{once:true})}if(title)title.textContent=lessons[i].title;if(num)num.textContent='LESSON '+String(i+1).padStart(2,'0');if(meta)meta.textContent=`Lesson ${i+1} of ${lessons.length} · YouTube Creator Course`;if(overlay)overlay.classList.remove('hidden');if(prev)prev.disabled=i===0;if(next)next.disabled=i===lessons.length-1;render()}
function updateControls(){if(!player)return;const d=player.duration||0,t=player.currentTime||0;if(seek)seek.value=d?Math.round(t/d*1000):0;if(timeDisplay)timeDisplay.textContent=`${fmt(t)} / ${fmt(d)}`;if(playBtn)playBtn.textContent=player.paused?'▶':'❚❚';if(muteBtn)muteBtn.textContent=player.muted||player.volume===0?'🔇':'🔊'}
function fmt(t){if(!Number.isFinite(t))return'0:00';const h=Math.floor(t/3600),m=Math.floor(t%3600/60),s=Math.floor(t%60).toString().padStart(2,'0');return h?`${h}:${String(m).padStart(2,'0')}:${s}`:`${m}:${s}`}
function toastMsg(x){if(!toast)return;toast.textContent=x;toast.classList.add('show');clearTimeout(toastMsg.t);toastMsg.t=setTimeout(()=>toast.classList.remove('show'),1200)}
function dashboard(){const p=pct(),completed=done.filter(i=>i<lessons.length).length;const last=Object.keys(positions).map(Number).filter(i=>i<lessons.length&&positions[i]>5).sort((a,b)=>(positions[b]||0)-(positions[a]||0))[0];const idx=last??Math.max(0,completed?Math.min(completed,lessons.length-1):0);const l=lessons[idx];if(l){const d=document.querySelector('#dashboardContinue');if(d)d.innerHTML=`<article class="continue-card"><div class="continue-thumb"><img src="${thumb(l,idx)}" alt="" loading="lazy"><span>▶</span></div><div class="continue-info"><span class="section-kicker">CONTINUE LEARNING</span><h3>${esc(l.title)}</h3><p>Lesson ${idx+1} of ${lessons.length}</p><div class="progress-line"><i id="dashboardBar" style="width:${p}%"></i></div><small>${p}% course progress</small><a class="primary-cta" href="lesson.html?lesson=${idx}">Continue →</a></div></article>`}else{const d=document.querySelector('#dashboardContinue');if(d)d.innerHTML='<div class="empty-dashboard">Your course is ready. Start your first lesson.</div>'}
const recent=lessons.slice(-6).reverse();const rg=document.querySelector('#recentGrid');if(rg)rg.innerHTML=recent.map((x)=>{const i=lessons.indexOf(x);return `<a class="lesson-card" href="lesson.html?lesson=${i}"><div class="lesson-thumb"><img loading="lazy" src="${thumb(x,i)}" alt=""><span>${String(i+1).padStart(2,'0')}</span></div><div class="lesson-card-body"><b>${esc(x.title)}</b><small>Lesson ${i+1} · ${done.includes(i)?'Completed':'Ready to watch'}</small></div></a>`}).join('');
const cats=[['🎥','Filming','Camera & shooting'],['💡','Production','Lighting & audio'],['✂️','Editing','Editing workflow'],['🚀','Publishing','Growth & strategy']];const cg=document.querySelector('#categoryGrid');if(cg)cg.innerHTML=cats.map(c=>`<a class="category-card" href="#recent"><span>${c[0]}</span><div><b>${c[1]}</b><small>${c[2]}</small></div><em>→</em></a>`).join('');if(document.querySelector('#heroLessons'))document.querySelector('#heroLessons').textContent=lessons.length;if(courseCount)courseCount.textContent='1';if(featuredCount)featuredCount.textContent=lessons.length;if(startCourse)startCourse.href=`lesson.html?lesson=${idx}`;if(courseGrid)courseGrid.innerHTML=`<article class="course-card dynamic-card"><div class="course-cover"><div class="cover-play">▶</div><span class="cover-label">FEATURED</span></div><div><h3>YouTube Creator Course</h3><p>Filming, lighting, audio, editing, publishing and creator growth — one practical curriculum.</p></div><div class="course-progress"><div><span>Progress</span><b>${p}%</b></div><i><u style="width:${p}%"></u></i></div><div class="course-meta"><span>${lessons.length} lessons · Self-paced</span><a class="course-link" href="lesson.html">Open course →</a></div></article>`;updateProgress()}
function togglePlay(){if(!player)return;if(player.paused){player.play().catch(()=>{});toastMsg('Playing')}else{player.pause();toastMsg('Paused')}}
player?.addEventListener('loadedmetadata',updateControls);player?.addEventListener('timeupdate',()=>{updateControls();if(lessons[current]&&player.currentTime>2){positions[current]=Math.floor(player.currentTime);localStorage.setItem(posKey,JSON.stringify(positions))}});player?.addEventListener('play',()=>{overlay?.classList.add('hidden');updateControls()});player?.addEventListener('pause',updateControls);player?.addEventListener('ended',()=>{if(!done.includes(current))done.push(current);localStorage.setItem(doneKey,JSON.stringify(done));render();dashboard();if(current<lessons.length-1)setTimeout(()=>select(current+1,true),450)});player?.addEventListener('error',()=>toastMsg('Video could not be loaded'));
playBtn?.addEventListener('click',togglePlay);overlay?.addEventListener('click',togglePlay);seek?.addEventListener('input',()=>{if(player.duration)player.currentTime=(Number(seek.value)/1000)*player.duration});muteBtn?.addEventListener('click',()=>{player.muted=!player.muted;updateControls()});speedBtn?.addEventListener('click',()=>speedMenu?.classList.toggle('open'));speedMenu?.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{player.playbackRate=Number(b.dataset.speed);if(speedBtn)speedBtn.textContent=b.dataset.speed+'×';speedMenu.classList.remove('open')}));pipBtn?.addEventListener('click',async()=>{try{if(document.pictureInPictureElement)await document.exitPictureInPicture();else await player.requestPictureInPicture()}catch(e){toastMsg('PiP unavailable')}});theaterBtn?.addEventListener('click',()=>wrap?.classList.toggle('theater'));fullscreenBtn?.addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await wrap.requestFullscreen()}catch(e){}});wrap?.addEventListener('mousemove',()=>{wrap.classList.add('controls-visible');clearTimeout(controlsTimer);controlsTimer=setTimeout(()=>{if(player&&!player.paused)wrap.classList.remove('controls-visible')},2500)});
if(prev)prev.onclick=()=>select(Math.max(0,current-1));if(next)next.onclick=()=>select(Math.min(lessons.length-1,current+1),true);if(search)search.oninput=render;if(themeBtn)themeBtn.onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('course-theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('course-theme')==='light')document.body.classList.add('light');
document.addEventListener('keydown',e=>{if(!player||['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(e.code==='Space'){e.preventDefault();togglePlay()}else if(e.key==='ArrowRight'){player.currentTime=Math.min(player.duration||0,player.currentTime+5);toastMsg('+5 seconds')}else if(e.key==='ArrowLeft'){player.currentTime=Math.max(0,player.currentTime-5);toastMsg('−5 seconds')}else if(e.key.toLowerCase()==='m'){player.muted=!player.muted;updateControls()}else if(e.key.toLowerCase()==='f'){fullscreenBtn?.click()}else if(e.key.toLowerCase()==='t'){theaterBtn?.click()}});
async function load(){try{const r=await fetch(MANIFEST+'?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('Manifest '+r.status);const files=await r.json();lessons=files.filter(x=>x.name&&/\.mp4$/i.test(x.name)).map(x=>({...x,title:x.title||cleanName(x.name),url:x.url||RAW+encodeURIComponent(x.name)})).sort(natural);dashboard();render();if(player&&lessons.length){const q=new URLSearchParams(location.search);select(Number(q.get('lesson'))||0)}}catch(e){console.error(e);if(list)list.innerHTML='<div style="padding:20px;color:#9aa3b2">Course manifest unavailable. Refresh in a moment.</div>'}}
load();