const MANIFEST='./videos.json';
const RAW='https://media.githubusercontent.com/media/LaxmanNepal/Videos/main/course/youtube/';
const player=document.querySelector('#player'),list=document.querySelector('#lessonList'),search=document.querySelector('#search');
const title=document.querySelector('#lessonTitle'),meta=document.querySelector('#lessonMeta'),num=document.querySelector('#lessonNumber');
const progress=document.querySelector('#progressText'),ring=document.querySelector('#ring'),playlistMeta=document.querySelector('#playlistMeta');
const prev=document.querySelector('#prevBtn'),next=document.querySelector('#nextBtn'),overlay=document.querySelector('#playerOverlay'),themeBtn=document.querySelector('#themeBtn');
const courseGrid=document.querySelector('#courseGrid'),courseCount=document.querySelector('#courseCount'),featuredCount=document.querySelector('#featuredCount'),startCourse=document.querySelector('#startCourse');
let lessons=[],current=0;
const doneKey='laxman-youtube-course-done-v1',posKey='laxman-youtube-course-position-v1';
let done=JSON.parse(localStorage.getItem(doneKey)||'[]'),positions=JSON.parse(localStorage.getItem(posKey)||'{}');
function cleanName(name){return name.replace(/\.mp4$/i,'').replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim()}
function natural(a,b){return a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'})}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function updateProgress(){const pct=lessons.length?Math.round(done.filter(i=>i<lessons.length).length/lessons.length*100):0;if(progress)progress.textContent=pct+'%';if(ring)ring.textContent=pct+'%';if(playlistMeta)playlistMeta.textContent=`${done.filter(i=>i<lessons.length).length} of ${lessons.length} completed`}
function render(){if(!list)return;const q=(search?.value||'').trim().toLowerCase();list.innerHTML='';lessons.forEach((l,i)=>{if(q&&!l.title.toLowerCase().includes(q))return;const b=document.createElement('button');b.className='lesson '+(i===current?'active ':'')+(done.includes(i)?'done':'');b.innerHTML=`<span class="lesson-num">${String(i+1).padStart(2,'0')}</span><span class="lesson-copy"><span class="lesson-title">${esc(l.title)}</span><span class="lesson-status">${done.includes(i)?'✓ Completed':'Watch lesson'}</span></span>`;b.onclick=()=>select(i);list.appendChild(b)});updateProgress()}
function select(i,autoplay=false){if(!player||!lessons[i])return;current=i;const l=lessons[i];player.src=l.url||RAW+encodeURIComponent(l.name);player.load();if(title)title.textContent=l.title;if(num)num.textContent='LESSON '+String(i+1).padStart(2,'0');if(meta)meta.textContent=`Lesson ${i+1} of ${lessons.length} · YouTube Creator Course`;if(overlay)overlay.classList.add('hidden');if(prev)prev.disabled=i===0;if(next)next.disabled=i===lessons.length-1;player.addEventListener('loadedmetadata',()=>{try{player.currentTime=positions[i]||0}catch(e){}},{once:true});render();document.querySelector('.player-col')?.scrollIntoView({behavior:'smooth',block:'start'});if(autoplay)player.play().catch(()=>{})}
function renderHomepage(){if(!courseGrid)return;if(courseCount)courseCount.textContent='1';if(featuredCount)featuredCount.textContent=lessons.length;if(startCourse)startCourse.href='lesson.html';courseGrid.innerHTML=`<article class="course-card"><div><div class="course-icon">▶</div><h3>YouTube Creator Course</h3><p>Learn filming, lighting, audio, editing, publishing and creator growth through practical step-by-step lessons.</p></div><div class="course-meta"><span>${lessons.length} lessons · Self-paced</span><a class="course-link" href="lesson.html">View course →</a></div></article>`}
player?.addEventListener('timeupdate',()=>{if(lessons[current]&&player.currentTime>2){positions[current]=Math.floor(player.currentTime);localStorage.setItem(posKey,JSON.stringify(positions))}});
player?.addEventListener('ended',()=>{if(!done.includes(current))done.push(current);localStorage.setItem(doneKey,JSON.stringify(done));render();if(current<lessons.length-1)setTimeout(()=>select(current+1,true),500)});
if(prev)prev.onclick=()=>select(Math.max(0,current-1));if(next)next.onclick=()=>select(Math.min(lessons.length-1,current+1),true);if(search)search.oninput=render;
if(themeBtn)themeBtn.onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('course-theme',document.body.classList.contains('light')?'light':'dark')};
if(localStorage.getItem('course-theme')==='light')document.body.classList.add('light');
async function load(){try{const r=await fetch(MANIFEST+'?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('Manifest '+r.status);const files=await r.json();lessons=files.filter(x=>x.name&&/\.mp4$/i.test(x.name)).map(x=>({...x,title:x.title||cleanName(x.name),url:x.url||RAW+encodeURIComponent(x.name)})).sort(natural);if(playlistMeta)playlistMeta.textContent=`${lessons.length} lessons`;renderHomepage();render();if(player&&lessons.length)select(0)}catch(e){console.error(e);if(playlistMeta)playlistMeta.textContent='Course manifest unavailable';if(list)list.innerHTML='<div style="padding:20px;color:#9aa3b2;font-size:12px">The course is being prepared. Please refresh in a moment.</div>'}}
load();